apiVersion: apps/v1
kind: Deployment
metadata:
  name: campusconnect
spec:
  replicas: 3
  selector:
    matchLabels:
      app: campusconnect
  template:
    metadata:
      labels:
        app: campusconnect
    spec:
      containers:
      - name: app
        image: campusconnect:1.0
        imagePullPolicy: Never        # use the image built inside Minikube
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet: { path: /actuator/health, port: 8080 }
          initialDelaySeconds: 20
        livenessProbe:
          httpGet: { path: /actuator/health, port: 8080 }
          initialDelaySeconds: 40
